# Generated by Django 4.2.2 on 2024-05-22 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.IntegerField(verbose_name='invoice_id')),
                ('category_id', models.IntegerField(verbose_name='category_id')),
                ('category', models.CharField(max_length=128, verbose_name='category_title')),
                ('author_id', models.IntegerField(verbose_name='author_id')),
                ('author', models.CharField(max_length=128, verbose_name='author_title')),
                ('catalog_title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='catalog_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('unit', models.CharField(max_length=32, verbose_name='unit')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='catalog_photo')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='total')),
                ('sale_quantity', models.IntegerField(verbose_name='sale_quantity')),
                ('available', models.IntegerField(verbose_name='available')),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='avg_rating')),
            ],
            options={
                'db_table': 'view_catalog',
                'ordering': ['category', 'catalog_title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='username')),
                ('first_name', models.CharField(max_length=128, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=128, verbose_name='last_name')),
                ('saleday', models.DateTimeField(verbose_name='saleday')),
                ('catalog_id', models.IntegerField(verbose_name='catalog_id')),
                ('author', models.CharField(max_length=128, verbose_name='author_title')),
                ('category', models.CharField(max_length=128, verbose_name='category')),
                ('catalog_title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='photo')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='delivery_address')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='rating')),
                ('details', models.TextField(blank=True, null=True, verbose_name='review_details')),
                ('final', models.TextField(blank=True, null=True, verbose_name='final')),
            ],
            options={
                'db_table': 'view_sale',
                'ordering': ['saleday'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=128, unique=True, verbose_name='author_name')),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='catalog_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='catalog_price')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('unit', models.CharField(max_length=32, verbose_name='unit')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='catalog_photo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_author', to='product.author')),
            ],
            options={
                'db_table': 'catalog',
                'ordering': ['catalog_title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=128, unique=True, verbose_name='category_title')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleday', models.DateTimeField(auto_now_add=True, verbose_name='saleday')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='delivery_address')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='rating')),
                ('details', models.TextField(blank=True, null=True, verbose_name='review_details')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_catalog', to='product.catalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sale',
                'ordering': ['saleday'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_title', models.CharField(max_length=256, verbose_name='organization_title')),
                ('address', models.CharField(max_length=128, verbose_name='address')),
                ('phone', models.CharField(max_length=128, verbose_name='phone')),
            ],
            options={
                'db_table': 'organization',
                'ordering': ['organization_title'],
                'indexes': [models.Index(fields=['organization_title'], name='organizatio_organiz_b60a20_idx')],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daten', models.DateTimeField(verbose_name='daten')),
                ('news_title', models.CharField(max_length=256, verbose_name='news_title')),
                ('details', models.TextField(verbose_name='news_details')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='news_photo')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['daten'],
                'indexes': [models.Index(fields=['daten'], name='news_daten_a29edb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datei', models.DateTimeField(verbose_name='datei')),
                ('numb', models.IntegerField(verbose_name='numb')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_organization', to='product.organization')),
            ],
            options={
                'db_table': 'invoice',
                'ordering': ['datei'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryday', models.DateTimeField(auto_now_add=True, verbose_name='deliveryday')),
                ('movement', models.CharField(choices=[('Application accepted for processing', 'Application accepted for processing'), ('Goods in transit', 'Goods in transit'), ('Stock item', 'Stock item'), ('The application is closed, the goods have been delivered', 'The application is closed, the goods have been delivered')], default='М', max_length=64, verbose_name='movement')),
                ('details', models.TextField(blank=True, null=True, verbose_name='delivery_details')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_delivery', to='product.sale')),
            ],
            options={
                'db_table': 'delivery',
                'ordering': ['deliveryday'],
            },
        ),
        migrations.AddField(
            model_name='catalog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_category', to='product.category'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_invoice', to='product.invoice'),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basketday', models.DateTimeField(auto_now_add=True, verbose_name='basketday')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_catalog', to='product.catalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_basket', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'basket',
                'ordering': ['basketday'],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['saleday'], name='sale_saleday_35a3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['datei'], name='invoice_datei_0a57d7_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['deliveryday'], name='delivery_deliver_395d39_idx'),
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['catalog_title'], name='catalog_catalog_d497ec_idx'),
        ),
        migrations.AddIndex(
            model_name='basket',
            index=models.Index(fields=['basketday'], name='basket_basketd_d70b82_idx'),
        ),
    ]
