# Generated by Django 4.2.2 on 2024-05-20 17:03
from pickle import FALSE, TRUE
from django.contrib.auth.models import User
from django.contrib.auth.models import Group

from django.db import migrations
# Подключаем модуль для работы с датой/веременем
from datetime import datetime, timedelta
# Подключаем модкль генерации случайных чисел
import random

# Получение случайного адреса (k - включает ли адрес квартиру)
def get_adres(k):
    ulica = ["ул. Абая", 
            "ул. Алиханова", 
            "ул. Архитектурная", 
            "ул. Баженова", 
            "ул. Байсеитовой", 
            "ул. Ботаническая", 
            "ул. Вавилова", 
            "ул. Воинов-интернационалистов", 
            "ул. Гастелло", 
            "ул. Гончарная", 
            "ул. Грибоедова", 
            "ул. Дружбы", 
            "ул. Ержанова",
            "ул. Ермекова",
            "ул. Жамбыла", 
            "ул. Заводская", 
            "ул. Защитная", 
            "ул. Ипподромная", 
            "ул. Караванная", 
            "ул. Карла Маркса", 
            "ул. Кирпичная", 
            "ул. Кооперации", 
            "ул. Космонавтов", 
            "ул. Курмангазы", 
            "ул. Луговая", 
            "ул. Луначарского", 
            "ул. Махметова", 
            "ул. Маяковского", 
            "ул. Металлистов", 
            "ул. Мира", 
            "ул. Некрасова", 
            "ул. Новоселов",
            "ул. Олимпийская", 
            "ул. Победы", 
            "ул. Привокзальная", 
            "ул. Рыскулова", 
            "ул. Садовая", 
            "ул. Сатпаева", 
            "ул. Степная", 
            "ул. Стремянная", 
            "ул. Таттимбета", 
            "ул. Университетская", 
            "ул. Фрунзе",
            "ул. Чехова", 
            "ул. Чайковского", 
            "ул. Шакирова", 
            "ул. Экибастузская", 
            "ул. Энтузиастов",
            "ул. Юбилейная",
            "ул. Южная"
        ]
    if (k==True):
        adres = random.choice(ulica) + ", " + str(random.randint(1, 200)) + "-" + str(random.randint(1, 200)) 
    else:
        adres = random.choice(ulica) + ", " + str(random.randint(1, 200)) 
    return adres

# Получение случайного телефона
def get_telefon():
    if random.randint(0, 1) == 1:
        telefon = "+7-701-"
    else:
        telefon = "+7-705-" 
    telefon = telefon + str(random.randint(0, 9)) + str(random.randint(0, 9)) + str(random.randint(0, 9)) + "-" + str(random.randint(0, 9)) + str(random.randint(0, 9)) + str(random.randint(0, 9)) + str(random.randint(0, 9)) 
    return telefon

# Добавить организацию 
def insert_organization(apps, parameters):   
    Organization = apps.get_model("product", "Organization")
    organization = Organization()
    organization.organization_title = parameters[0]
    organization.address = parameters[1]
    organization.phone = parameters[2]
    organization.save()
    organization

# Добавить приходную накладную 
def insert_invoice(apps, parameters):   
    Invoice = apps.get_model("product", "Invoice")
    invoice = Invoice()
    invoice.organization_id = parameters[0]
    invoice.datei = parameters[1]
    invoice.numb = parameters[2]
    invoice.save()
    invoice

# Найти или Добавить Автора
global dict_author
dict_author = {}

def get_author(apps, val):   
    # Поиск автора
    if val in dict_author.values():
        for k, v in dict_author.items():
            if v == val:
                return k    
    else:
        Author = apps.get_model("product", "Author")
        author = Author()
        author.author_name = val
        author.save()
        dict_author[author.id] = author.author_name
        return author.id

# Найти или Добавить Категорию
global dict_category
dict_category = {}

def get_category(apps, val):   
    # Поиск категории
    if val in dict_category.values():
        for k, v in dict_category.items():
            if v == val:
                return k    
    else:
        Category = apps.get_model("product", "Category")
        category = Category()
        category.category_title = val
        category.save()
        dict_category[category.id] = category.category_title
        return category.id

# Добавить товар 
global dict_catalog_price
dict_catalog_price = {}

def insert_catalog(apps, param_catalog):   
    # Добавить товар
    Catalog = apps.get_model("product", "Catalog")
    catalog = Catalog()
    catalog.invoice_id = param_catalog[0]
    catalog.category_id = param_catalog[1]
    catalog.author_id = param_catalog[2]
    catalog.catalog_title = param_catalog[3]
    catalog.details = param_catalog[4]
    catalog.price = param_catalog[5]
    catalog.quantity = param_catalog[6]
    catalog.unit = param_catalog[7]
    catalog.photo = param_catalog[8]
    catalog.save()
    dict_catalog_price[catalog.id] = catalog.price    
    return

# Добавить продажу, отзыв и доставку
def insert_sale(apps, param_sale):   
    # Продажа
    Sale = apps.get_model("product", "Sale")
    # Доставка
    Delivery = apps.get_model("product", "Delivery")
    
    sale = Sale()
    sale.saleday = param_sale[0]
    sale.catalog_id = param_sale[1]
    sale.price = param_sale[2]
    sale.quantity = param_sale[3]
    sale.user_id = param_sale[4]
    sale.address = param_sale[5]
    sale.rating = param_sale[6]
    sale.details= param_sale[7]
    sale.save()
    sale.saleday = param_sale[0]
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    delivery.deliveryday = sale.saleday
    delivery.movement = "Заявка принята в обработку"
    delivery.details="Заявка принята в обработку"
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.movement = "Товар в пути"
    delivery.details="Товар в пути"
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    delivery.deliveryday = sale.saleday + timedelta(days=1)
    delivery.movement = "Товар на складе"
    delivery.details="Товар на складе"
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(days=1)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    delivery.deliveryday = sale.saleday + timedelta(days=2)
    delivery.movement = "Заявка закрыта, товар доставлен"
    delivery.details="Заявка закрыта, товар доставлен"
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(days=2)
    delivery.save()
    return

# Добавить Новости
def insert_news(apps, param):
    News = apps.get_model("product", "News")
    news = News()
    news.daten = param[0]
    news.news_title = param[1]
    news.details = param[2]
    news.photo = param[3]
    news.save()
    return 

# Начальные данные 
def new_data(apps, schema_editor):
    try:
        # Суперпользователь id=1
        user = User.objects.create_superuser(username='root',
        email='shop240524@mail.ru',
        first_name='Марат', 
        last_name='Баядилов',
        password='SsNn5678+-@')
        print("Суперпользователь создан")
    
        # Группа менеджеров
        managers = Group.objects.get_or_create(name = 'Managers')
        managers = Group.objects.get(name='Managers')
        print("Группа менеджеров создана")
    
        # Пользователь с ролью менеджера id=2
        user = User.objects.create_user(username='manager', password='Ss0066+-', email='manager@mail.ru', first_name='Алмат', last_name='Кужахметов')
        managers.user_set.add(user)
        print("Менеджер добавлен в группу менеджеров")

        # Простые пользователи (заявители) id3-22
        user = User.objects.create_user(username='user1', password='Uu0066+-', email='user1@mail.ru', first_name='Вадим', last_name='Воронцов', last_login=datetime.now())
        user = User.objects.create_user(username='user2', password='Uu0066+-', email='user2@mail.ru', first_name='Владимир', last_name='Кожанов', last_login=datetime.now())
        user = User.objects.create_user(username='user3', password='Uu0066+-', email='user3@mail.ru', first_name='Станислав', last_name='Самашинский', last_login=datetime.now())
        user = User.objects.create_user(username='user4', password='Uu0066+-', email='user4@mail.ru', first_name='Андрей', last_name='Ковганюк', last_login=datetime.now())
        user = User.objects.create_user(username='user5', password='Uu0066+-', email='user5@mail.ru', first_name='Борис', last_name='Перепелица', last_login=datetime.now())
        user = User.objects.create_user(username='user6', password='Uu0066+-', email='user6@mail.ru', first_name='Юлия', last_name='Фурман', last_login=datetime.now())
        user = User.objects.create_user(username='user7', password='Uu0066+-', email='user7@mail.ru', first_name='Дарья', last_name='Толстых', last_login=datetime.now())
        user = User.objects.create_user(username='user8', password='Uu0066+-', email='user8@mail.ru', first_name='Анастасия', last_name='Коршунова', last_login=datetime.now())
        user = User.objects.create_user(username='user9', password='Uu0066+-', email='user9@mail.ru', first_name='Ольга', last_name='Муравьева', last_login=datetime.now())
        user = User.objects.create_user(username='user10', password='Uu0066+-', email='user10@mail.ru', first_name='Роман', last_name='Когай', last_login=datetime.now())
        user = User.objects.create_user(username='user11', password='Uu0066+-', email='user11@mail.ru', first_name='Вячеслав', last_name='Федоров', last_login=datetime.now())
        user = User.objects.create_user(username='user12', password='Uu0066+-', email='user12@mail.ru', first_name='Антон', last_name='Корнеенков', last_login=datetime.now())
        user = User.objects.create_user(username='user13', password='Uu0066+-', email='user13@mail.ru', first_name='Светлана', last_name='Борисенко', last_login=datetime.now())
        user = User.objects.create_user(username='user14', password='Uu0066+-', email='user14@mail.ru', first_name='Екатерина', last_name='Рудич', last_login=datetime.now())
        user = User.objects.create_user(username='user15', password='Uu0066+-', email='user15@mail.ru', first_name='Алина', last_name='Увалиева', last_login=datetime.now())
        user = User.objects.create_user(username='user16', password='Uu0066+-', email='user16@mail.ru', first_name='Георгий', last_name='Соин', last_login=datetime.now())
        user = User.objects.create_user(username='user17', password='Uu0066+-', email='user17@mail.ru', first_name='Оксана', last_name='Гавва', last_login=datetime.now())
        user = User.objects.create_user(username='user18', password='Uu0066+-', email='user18@mail.ru', first_name='Галина', last_name='Ким', last_login=datetime.now())
        user = User.objects.create_user(username='user19', password='Uu0066+-', email='user19@mail.ru', first_name='Михаил', last_name='Востриков', last_login=datetime.now())
        user = User.objects.create_user(username='user20', password='Uu0066+-', email='user20@mail.ru', first_name='Артур', last_name='Орлов', last_login=datetime.now())
        print("Созданы простые пользователи")

        # Организации
        parameters = ["Параллель, ООО", "Новосибирск, Академика Ржанова, 4/1", "83833302698"]
        insert_organization(apps, parameters)
        parameters = ["ООО «Формат»", "ranok-vas@mail.ru", "84957992110"]
        insert_organization(apps, parameters)
        parameters = ["ООО «ИСКАТЕЛЬКНИГА»", "Москва, ул. Новодмитровская, д. 5А", "84956855901"]
        insert_organization(apps, parameters)
        parameters = ["Book Книга", "sales@bookniga.com", "89093762076"]
        insert_organization(apps, parameters)
        parameters = ["ООО «ФОРМАТ»", "format1-lybov@yandex.ru", "89103220711"]
        insert_organization(apps, parameters)
        
        print("Созданы организации")

        # Приходные накладные
        parameters = [1, datetime.now() - timedelta(days=60) + timedelta(minutes=random.randint(1, 240)), 1]
        insert_invoice(apps, parameters)
        parameters = [2, datetime.now() - timedelta(days=59) + timedelta(minutes=random.randint(1, 240)), 2]
        insert_invoice(apps, parameters)
        parameters = [3, datetime.now() - timedelta(days=58) + timedelta(minutes=random.randint(1, 240)), 3]
        insert_invoice(apps, parameters)
        parameters = [4, datetime.now() - timedelta(days=57) + timedelta(minutes=random.randint(1, 240)), 4]
        insert_invoice(apps, parameters)
        parameters = [5, datetime.now() - timedelta(days=56) + timedelta(minutes=random.randint(1, 240)), 5]
        insert_invoice(apps, parameters)
        parameters = [1, datetime.now() - timedelta(days=55) + timedelta(minutes=random.randint(1, 240)), 6]
        insert_invoice(apps, parameters)
        parameters = [2, datetime.now() - timedelta(days=54) + timedelta(minutes=random.randint(1, 240)), 7]
        insert_invoice(apps, parameters)
        parameters = [3, datetime.now() - timedelta(days=53) + timedelta(minutes=random.randint(1, 240)), 8]
        insert_invoice(apps, parameters)
        parameters = [4, datetime.now() - timedelta(days=52) + timedelta(minutes=random.randint(1, 240)), 9]
        insert_invoice(apps, parameters)
        parameters = [5, datetime.now() - timedelta(days=51) + timedelta(minutes=random.randint(1, 240)), 10]
        insert_invoice(apps, parameters)
        
        print("Созданы Приходные накладные")

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [1, get_category(apps, "Проза"), get_author(apps, "Васильев Борис Львович"), "А зори здесь тихие...", """ Пять совсем еще юных девушек‑зенитчиц под руководством старшины вступают в неравный бой с отрядом немецких диверсантов. Об этом великом, однако не попавшем в сводки военных событий подвиге повесть «А зори здесь тихие...» — шедевр русской «военной прозы», одно из самых проникновенных и трагических произведений о Великой Отечественной войне. 
	 Действие повести «Завтра была война» происходит накануне Великой Отечественной войны. Это история о школьниках, их взрослении, первом нравственном выборе и противостоянии, история о выпускниках, которым совсем скоро предстоит взять в руки оружие и отправиться на фронт — защищать Родину.""", 226, 10, "шт.", "images/catalog01.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 1
        user_id = 3
        parameters = [datetime.now() - timedelta(days=30) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Внешнее оформление:Превосходное
Подача материала и манера письма:Очень увлекательная
Сюжет:Захватывающий"""]
        insert_sale(apps, parameters)
        catalog_id = 1
        user_id = 4
        parameters = [datetime.now() - timedelta(days=29) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """В книге собрана две повести Васильева Б.Л. «А зори здесь тихие» и «Завтра была война»
Как-то в школьное время пропустила чтение этих двух произведений. Решила наверстать.
Без лишних комментариев, я рыдала. До сих пор щемящее ощущение в груди после прочтения """]
        insert_sale(apps, parameters)
        
        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [1, get_category(apps, "Проза"), get_author(apps, "Чехов Антон Павлович"), "Рассказы", """Проникновенная «Дама с собачкой» – и печальная «Попрыгунья». Хлесткий «Человек в футляре» – и озорные «Мальчики». Беспощадная «Палата номер шесть» – и трогательная «Каштанка». В этот сборник вошли рассказы и повести разных лет, серьезные и смешные, юмористические и трагические, взрослые и детские. Однако о чем бы ни писал великий Чехов – неизменными всегда оставались его поразительное чувство слова и глубокое понимание человеческой природы.
Теги: Чехов, Антон Павлович Чехов, рассказы Чехова, рассказы, сборник рассказов, книги, книга, книги классика, книги художественная литература, книжка, книжки, художественная литература, книги художественная литература, литература, классическая литература, всемирная литература, приключенческая литература, художественная литература классика, классическая литература книги, классика, мировая классика, книги классика русская, русская литература, русская литература для всех, школьная литература, школьная программа.""", 199, 10, "шт.", "images/catalog02.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 2
        user_id = 5
        parameters = [datetime.now() - timedelta(days=28) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Сюжет:Интересный
Внешнее оформление:Красивое
Подача материала и манера письма:Обычная
Хорошая книга, бумага не идеальная, но читать приятно"""]
        insert_sale(apps, parameters)
        catalog_id = 2
        user_id = 6
        parameters = [datetime.now() - timedelta(days=28) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Отличная книга, к покупке рекомендую"""]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [1, get_category(apps, "Проза"), get_author(apps, "Достоевский Федор Михайлович"), "Преступление и наказание", """"Преступление и наказание" (1866) — одно из самых значительных произведений в истории мировой литературы. Это и глубокий филососфский роман, и тонкая психологическая драма, и захватывающий детектив, и величественная картина мрачного города, в недрах которого герои грешат и ищут прощения, жертвуют собой и отрекаются от себя ради ближних и находят успокоение в смирении, покаянии, вере. Главный герой романа Родион Раскольников решается на убийство, чтобы доказать себе и миру, что он не "тварь дрожащая", а "право имеет". Главным предметом исследования писателя становится процесс превращения добропорядочного, умного и доброго юноши в убийцу, а также то, как совершивший преступление Раскольников может искупить свою вину. 
Теги: Преступление и наказание, Достоевский, Федор Достоевский, Преступление и наказание Достоевский, Достоевский Преступление и наказание, Идиот Достоевский, Бесы Достоевский, Достоевский Идиот, Белые ночи Достоевский, Достоевский Бесы, книги, книга, книги классика, книги художественная литература, книжка, книжки, книги романы, романы, роман, книга роман, художественная литература, книги художественная литература, литература, классическая литература, всемирная литература, художественная литература классика, классическая литература книги, классика, мировая классика, книги классика русская, художественная литература для детей, книги для подростков, книга для подростков.""", 265, 10, "шт.", "images/catalog03.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 3
        user_id = 7
        parameters = [datetime.now() - timedelta(days=27) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Хорошая книга, удобная можно носить с собой. Доставка быстрая. Обложка и переплет (склейка) достойная. Ну а содержание на высоте как впрочим и весь Достоевский! """]
        insert_sale(apps, parameters)
        catalog_id = 3
        user_id = 8
        parameters = [datetime.now() - timedelta(days=27) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Внешнее оформление:Красивое
Подача материала и манера письма:Очень увлекательная
Сюжет:Захватывающий"""]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [2, get_category(apps, "Проза"), get_author(apps, "Пушкин Александр Сергеевич"), "Капитанская дочка", """А. С. Пушкин вошел в русскую культуру не только как великий Поэт,  но и как замечательный прозаик и драматург. В этот том включены наиболее значительные и известные прозаические произведения автора, в которых он предстает историком, бытописателем, тонким психологом (знатоком человеческой души) и великолепным рассказчиком: «Арап Петра Великого», «Повести покойного Ивана Петровича Белкина», «Дубровский», «Пиковая дама», «История Пугачева» и «Капитанская дочка».""", 193, 10, "шт.", "images/catalog04.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 4
        user_id = 9
        parameters = [datetime.now() - timedelta(days=26) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Как всегда Классная Классика превосходна!"""]
        insert_sale(apps, parameters)
        catalog_id = 4
        user_id = 10
        parameters = [datetime.now() - timedelta(days=26) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Очень достойный подарок!"""]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [2, get_category(apps, "Проза"), get_author(apps, "Булгаков Михаил Афанасьевич"), "Бег", """﻿В данный сборник вошли пьесы Михаила Булгакова, не опубликованные при жизни автора.
Действие пьесы "Бег" разворачивается во время Гражданской войны; это драма о боли и беде русской эмиграции. "Иван Васильевич" — озорная комедия, позднее послужившая основой для сценария любимого в нашей стране фильма "Иван Васильевич меняет профессию". "Адам и Ева" — пьеса-антиутопия о жизни после техногенной катастрофы. "Последние дни" — биографическая трагедия о последних днях Пушкина, написанная к столетию со дня гибели поэта.
Неизменным остается в них огромный литературный талант Булгакова, его поразительное чувство слова, умение выстраивать яркие сюжеты и запоминающиеся характеры при помощи минимальных выразительных средств.""", 189, 10, "шт.", "images/catalog05.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 5
        user_id = 11
        parameters = [datetime.now() - timedelta(days=25) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Хорошее издание, состоящее из четырёх произведений Булгакова.
Плотные страницы, не просвечивают. Не выбеленные, поэтому глаза не устают читать.
Уменьшенный формат в мягкой обложке - удобно брать с собой в дорогу. """]
        insert_sale(apps, parameters)
        catalog_id = 5
        user_id = 12
        parameters = [datetime.now() - timedelta(days=25) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Внешнее оформление:Превосходное
Подача материала и манера письма:Очень увлекательная
Сюжет:Захватывающий"""]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [2, get_category(apps, "Проза"), get_author(apps, "Островский Николай"), "Как закалялась сталь", """«Раньше я решительно протестовал против того, что эта вещь автобиографична, но теперь это бесполезно. В книге дана правда без всяких отклонений. Ведь ее писал не писатель. Я до этого не написал ни одной строки», — признавался Николай Островский за два месяца до смерти. Ни одной строки!.. На тот момент ему было тридцать два года. Он был обездвижен и слеп и вот уже восемь лет прикован к постели. Книгу, ставшую эмблемой эпохи и учебником жизни для миллионов людей, написал человек, лишенный возможности видеть и двигаться, бывший кочегар, прошедший сквозь горнило революции и Гражданской войны, яростный строитель и защитник нового государства, сражавшийся за его идеи сначала с помощью сабли, а потом — слова.""", 168, 10, "шт.", "images/catalog06.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 6
        user_id = 13
        parameters = [datetime.now() - timedelta(days=25) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Внешнее оформление:Красивое
Подача материала и манера письма:Очень увлекательная
Сюжет:Интересный
Достоинства
мягкая книжка, четкий текст, не мелкий не крупный, без картинок."""]
        insert_sale(apps, parameters)
        catalog_id = 6
        user_id = 14
        parameters = [datetime.now() - timedelta(days=24) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Интересная книга, все воспринимается по новому"""]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [3, get_category(apps, "Проза"), get_author(apps, "Толстой Лев Николаевич"), "Воскресение", """Роман, оказавший огромное влияние не только на отечественную, но и мировую культуру, экранизированный в нашей стране и за рубежом, множество раз.
Князь Нехлюдов, умный и пресыщенный эстет и сибарит, с ужасом узнает на суде в проститутке, обвиняемой в отравлении клиента, Катюшу Маслову — чистую, нежную девушку, которую он, со скуки, соблазнил когда‑то, — и с легкостью бросил, толкнув на дно жизни. Терзаемый муками совести, он готов на все, — даже жениться на осужденной каторжанке и последовать за ней в Сибирь. Но удастся ли ему вымолить прощение? И примет ли Катюша жертву от мужчины, погубившего ее когда‑то?.""", 265, 10, "шт.", "images/catalog07.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 7
        user_id = 15
        parameters = [datetime.now() - timedelta(days=23) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """отличное произведение, очень хорошая сдержанная обложка """]
        insert_sale(apps, parameters)
        catalog_id = 7
        user_id = 16
        parameters = [datetime.now() - timedelta(days=22) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Достоинства
Качество бумаги хорошее, быстрая доставка 
Недостатки
нет 
Комментарий
Книга очень интересная, рекомендую """]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [3, get_category(apps, "Проза"), get_author(apps, "Шукшин Василий"), "Калина красная", """Творчество Василия Шукшина (1929–1974) – выдающееся явление 1960–1970-х годов. Талант этой личности проявился в актерском, режиссерском, сценарном мастерстве, однако именно литературные произведения принесли Шукшину всенародную славу. Повести и рассказы писателя  переведены более чем на двадцать языков и по праву считаются достоянием русской литературы ХХ века. 
В настоящий сборник вошли киноповести «Калина красная», «Печки-лавочки», «Живет такой парень», «Позови меня в даль светлую…», «Брат мой…», которые легли в основу широко известных, любимых фильмов.""", 177, 10, "шт.", "images/catalog08.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 8
        user_id = 17
        parameters = [datetime.now() - timedelta(days=23) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Когда читаешь про знакомство с родственниками , представляешь себя на месте главного героя."""]
        insert_sale(apps, parameters)
        catalog_id = 8
        user_id = 18
        parameters = [datetime.now() - timedelta(days=22) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """удобная книга, место много не займёт, можно взять в дорогу"""]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [3, get_category(apps, "Проза"), get_author(apps, "Куприн Александр Иванович"), "Яма", """Повесть «Яма» А. И. Куприн начал писать в 1909 году и завершил работу через шесть лет. Книга о жизни проституток вызвала скорее осуждение, чем сочувствие или понимание. Автора обвиняли в безнравственности и чрезмерном натурализме. Резко негативным было отношение к повести Л. Н. Толстого (кстати, автора скандальной «Крейцеровой сонаты»), который так и не смог дочитать ее до конца: «отвратительно», «грубость циническая», «это мерзость», «так гадко». И словно в пику Толстому один из героев «Ямы» говорит: «…Наши художники слова — самые совестливые и самые искренние во всем мире художники — почему-то до сих пор обходили проституцию и публичный дом. Почему? Право, мне трудно ответить на это. Может быть, у них не хватает ни времени, ни самоотверженности, ни самообладания вникнуть с головой в эту жизнь и подсмотреть ее близко, без предубеждения, без громких фраз, без овечьей жалости, во всей ее чудовищной простоте и будничной деловитости. Ах, какая бы это получилась громадная, потрясающая и правдивая книга». Куприн сумел создать книгу, действительно потрясающую своей правдивостью, и посвятил ее матерям и юношеству.""", 155, 10, "шт.", "images/catalog09.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 9
        user_id = 19
        parameters = [datetime.now() - timedelta(days=23) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Прекрасная книга. Поистине проникаешься духом того времени, книга мягкой пеленой окутывает тебя атмосферой того времени. Понимаешь, что в той эпохе, о которой когда-то нам пели «и вальсы Шуберта и хруст французской булки» есть и другая, очень грустная и тяжелая сторона. Браво русской литературе. Спасибо издателю"""]
        insert_sale(apps, parameters)
        catalog_id = 9
        user_id = 20
        parameters = [datetime.now() - timedelta(days=22) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 4, """Книга пришла упакована, бумага хорошая. Куприн пишет изумительно, всем советую читать его произведения, очень актуальные """]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [4, get_category(apps, "Проза"), get_author(apps, "Гоголь Николай Васильевич"), "Вечера на хуторе близ Диканьки", """Одно из лучших произведений классической отечественной литературы. Книга, которая вот уже почти два столетия в равной степени любима читателями всех возрастов. Сам Пушкин восхищенно писал об этом сборнике: "Вот настоящая весёлость, искренняя, непринуждённая, без жеманства, без чопорности. А местами какая поэзия!.."
Перед нами оживает поразительный мир украинского фольклора – мир русалок, ведьм, призраков, демонов и чертей. Мир, где самые удивительные, а порой и страшные события описаны с мягким и лукавым, типично украинским юмором и соседствуют с колоритно изображенным крестьянским бытом XIX века. """, 199, 10, "шт.", "images/catalog10.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 10
        user_id = 21
        parameters = [datetime.now() - timedelta(days=21) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Внешнее оформление:Красивое
Подача материала и манера письма:Очень увлекательная
Сюжет:Захватывающий"""]
        insert_sale(apps, parameters)
        catalog_id = 10
        user_id = 22
        parameters = [datetime.now() - timedelta(days=20) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Внешнее оформление:Обычное
Подача материала и манера письма:Очень увлекательная
Сюжет:Интересный"""]
        insert_sale(apps, parameters)
        
        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [4, get_category(apps, "Поэзия"), get_author(apps, "Лермонтов Михаил Юрьевич"), "Мцыри. Поэмы. Стихотворения", """Михаил Юрьевич Лермонтов (1814—1841) — один из самых популярных русских поэтов и писателей, яркий представитель романтизма. Сочетание простоты и возвышенности, естественности и оригинальности, его умение объективно показывать характеры героев, раскрывая одного персонажа через восприятие другим, и по сей день восхищают и читателей, и критиков. 
В книге собраны избранные стихотворения Лермонтова разных лет, а также знаменитые поэмы «Кавказский пленник», «Беглец», «Демон», «Мцыри» и другие.""", 243, 10, "шт.", "images/catalog11.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 11
        user_id = 3
        parameters = [datetime.now() - timedelta(days=19) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Шедевры русской поэзии"""]
        insert_sale(apps, parameters)
        catalog_id = 11
        user_id = 4
        parameters = [datetime.now() - timedelta(days=18) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Очень увлекательная"""]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [4, get_category(apps, "Поэзия"), get_author(apps, "Некрасов Николай Алексеевич"), "Кому на Руси жить хорошо", """Поэма «Кому на Руси жить хорошо» Н. Некрасова — путешествие-странствие героев в поисках счастливого человека на Руси, итоговое произведение поэта, народная эпопея, куда вошел весь многовековой опыт крестьянской жизни, все знания о народе, собранные поэтом «по словечку» в течение двадцати лет. Сила поэта Н.А. Некрасова — в особой доверительности его художественных интонаций: они обращены к сокровенным сторонам человеческой натуры, угнетаемой повседневностью, испытываемой на прочность социальными конфликтами. 
Фольклорная основа языка поэмы помогла Н. Некрасову точнее и полноценнее выразить русскую душу.""", 428, 10, "шт.", "images/catalog12.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 12
        user_id = 5
        parameters = [datetime.now() - timedelta(days=17) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Отличная книжка. Качество хорошее. Все пропечатано """]
        insert_sale(apps, parameters)
        catalog_id = 12
        user_id = 6
        parameters = [datetime.now() - timedelta(days=16) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """во-первых, очень легко читается, прекрасная книга, прекрасный автор, ну а во-вторых каждое страница подписано, именно что происходит в этом абзаце, отдельное спасибо)"""]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [5, get_category(apps, "Поэзия"), get_author(apps, "Пушкин Александр Сергеевич"), "Евгений Онегин. Поэмы", """Александр Сергеевич Пушкин (1799—1837) — великий русский поэт, создатель новой литературы, достигший необычайной легкости языка, изысканности и точности выражения мысли.
В сборник вошли его избранные произведения, составляющие «золотой фонд» классической русской литературы. 
Роман в стихах «Евгений Онегин» — энциклопедия пушкинской эпохи и культовая история несчастной любви, и поэмы «Руслан и Людмила», «Бахчисарайский фонтан», «Цыганы», «Граф Нулин», «Полтава» и «Медный всадник».""", 295, 10, "шт.", "images/catalog13.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 13
        user_id = 7
        parameters = [datetime.now() - timedelta(days=15) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Книга пришла не повреждена, твердая обложка, напечатано хорошо всё. Никаких нареканий нет!Пришла быстро. Рекомендую продавца!!! """]
        insert_sale(apps, parameters)
        catalog_id = 13
        user_id = 3
        parameters = [datetime.now() - timedelta(days=14) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """обожаю Пушкина, собрала всю коллекцию его произведений в этом издании. Сдающим ОГЭ по литературе шлю привет """]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [5, get_category(apps, "Поэзия"), get_author(apps, "Мандельштам Осип Эмильевич"), "Нежнее нежного лицо твое.", """Эмоциональный настрой лирики Мандельштама преисполнен тем, что критики называли «душевной неуютностью». И акцентированная простота повсфедневных мелочей, из которых он выстраивал свою поэтическую реальность, лишь подчеркивает тоску и беспокойство незаурядного человека, которому выпало на долю жить в «перевернутом мире».
В это издание вошли как хорошо знакомые, так и менее известные широкому кругу читателей стихи русского поэта Осипа Мандельштама. Оно включает прижизненные поэтические сборники автора («Камень», «Tristia», «Стихи 1921–1925»), стихи 1930–1937 годов, объединенные хронологически, а также стихотворения, не вошедшие в собрания.""", 333, 10, "шт.", "images/catalog14.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 14
        user_id = 4
        parameters = [datetime.now() - timedelta(days=15) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Мандельштам, как всегда, прекрасен. """]
        insert_sale(apps, parameters)
        catalog_id = 14
        user_id = 5
        parameters = [datetime.now() - timedelta(days=14) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Прекрасный сборник стихов, все нужное под одной обложкой. """]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [5, get_category(apps, "Поэзия"), get_author(apps, "Гумилев Николай Степанович"), "Стихотворения", """Сборник стихов Николая Гумилева откроет читателю дверь в мир экзотических приключений, истинного благородства и подлинной романтики.
Один из самых ярких поэтов Серебряного века с трагической судьбой. В 1921 году он был арестован и расстрелян, а его книги запрещены к изданию в Советском Союзе. За «железным занавесом» не было места его отважным конквистадорам, изящным каравеллам, загадочным странам и волшебным скрипкам; чуждой были его тончайшая любовная лирика и глубокая философия. Но мы можем насладиться всем этим прямо сейчас. Эти стихи — настоящее противоядие от цинизма нашего времени, спасение от депрессии и прозы быта. 
Строки Гумилева сильнее, чем любая мотивационная литература, вдохновляют жить полной жизнью, искать свой путь, путешествовать, любить и смело отстаивать самые высокие идеалы.""", 599, 10, "шт.", "images/catalog15.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 15
        user_id = 6
        parameters = [datetime.now() - timedelta(days=15) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Иногда вечером, иногда в период творческого кризиса люблю почитать. Иногда выучить, с выражением рассказать. Помогают при творческом кризисе. Очень рад, что приобрёл. """]
        insert_sale(apps, parameters)
        catalog_id = 15
        user_id = 7
        parameters = [datetime.now() - timedelta(days=14) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """К сожалению в этом сборнике нет моего любимого стихотворения «Крест». Зато есть другие) . Хороший сборник в рабочем варианте печати"""]
        insert_sale(apps, parameters)
        #parameters = [datetime.now() - timedelta(days=13) + timedelta(minutes=random.randint(1, 240)), catalog_id, user_id, "Вопрос?", "Ответ"]		
        #insert_question(apps, parameters) 

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [6, get_category(apps, "Бизнес-литература"), get_author(apps, "Филип Котлер, Котлер Филип"), "Маркетинг от А до Я. 80 концепций, которые должен знать каждый менеджер", """• Книга написана гуру маркетинга и стала настольной для миллионов специалистов во всем мире.
• Она дает наилучшее представление как о классических инструментах маркетинга, которые прошли испытание временем, так и об инновационных разработках, которые стали использоваться только в последние годы.
• В ней в легко усваиваемой форме представлены свежие идеи, оценки и конкретные практические рекомендации, которые побуждают к действию.
80 ключевых концепций эффективного маркетинга, их содержание и значение для современного бизнеса. Автор собрал и переосмыслил основные принципы и лучшие методы эффективного и инновационного маркетинга.""", 560, 10, "шт.", "images/catalog16.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 16
        user_id = 4
        parameters = [datetime.now() - timedelta(days=13) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Полезность материала:Познавательно
Глубина мысли:Глубокая
Внешнее оформление:Превосходное"""]
        insert_sale(apps, parameters)
        catalog_id = 16
        user_id = 5
        parameters = [datetime.now() - timedelta(days=12) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """маркетолог не маркетолог, если не читал эту книгу. азбука маркетинга"""]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [6, get_category(apps, "Бизнес-литература"), get_author(apps, "Ильяхов Максим, Сарычева Людмила"), "Пиши, сокращай 2025: Как создавать сильный текст", """«Пиши, сокращай» — книга о создании текста для всех, кто пишет по работе, неважно, работает ли человек профессиональным автором или текст — его дополнительная задача. Сотрудникам предприятий советы из книги помогут четко доносить пользу своих продуктов до потенциальных клиентов, договариваться с коллегами, руководителями, знакомыми. Журналистам — создавать интересные статьи и публикации в соцсетях. Авторы на примерах рассказывают, в каком порядке подавать информацию, без каких слов текст станет более ясным, как убедить читателя дочитать до конца и всегда ли это нужно. Материал «Пиши, сокращай» подан так, чтобы читателям легко было его охватить и применить на практике: кому-то понадобятся простые приемы редактуры на уровне слов, а кто-то углубится в тему отношений с читателями. И каждый найдет в книге полезное для себя.""", 825, 10, "шт.", "images/catalog17.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 17
        user_id = 6
        parameters = [datetime.now() - timedelta(days=11) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Хорошая книга для начинающего копирайтера,с помощью нее вы сможете развить свои навыки написания текстов
Прочитала пока что еще совсем малую часть,но уже многое узнала
Единственное-не поняла взаимосвязь птицы на обложке,по моему не особо выписывается под это все"""]
        insert_sale(apps, parameters)
        catalog_id = 17
        user_id = 7
        parameters = [datetime.now() - timedelta(days=10) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Читаю. Пока все по делу, с примерами. Интересно."""]
        insert_sale(apps, parameters)
        #parameters = [datetime.now() - timedelta(days=9) + timedelta(minutes=random.randint(1, 240)), catalog_id, user_id, "Вопрос?", "Ответ"]		
        #insert_question(apps, parameters) 

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [6, get_category(apps, "Бизнес-литература"), get_author(apps, "Тарасов Владимир Константинович"), "Искусство управленческой борьбы. Технологии перехвата и удержания управления", """Каждый из нас ежедневно оказывается вовлеченным в разнообразные ситуации, связанные с борьбой за право контролировать происходящее и управлять обстоятельствами. Мы должны преодолевать сознательное или непреднамеренное сопротивление окружающих, исполнять взятые на себя обязательства, отстаивать свои интересы и убеждения.
Каждый из нас управляет миром, хотя, может быть, делает это плохо: камень на дороге управляет повозкой; ребенок, еще не умея говорить, уже управляет родителями; собака управляет хозяином, а кошка – собакой. Все управляю всеми. Не стыдно управлять миром, стыдно делать это плохо. Управлять можно всем и всеми, в любой ситуации и из любой точки, – надо лишь знать, как это делать.
Эта книга предлагает читателю эффективную систему управленческих навыков, своеобразную «философию жизни», соединяющую мудрость древних традиций с последними достижениями психологии и менеджмента. В какие бы обстоятельства ни поставила вас жизнь, эта книга научит вас достойно выходить из любой конфликтной ситуации, которыми так богата жизнь каждого активного человека.""", 1315, 10, "шт.", "images/catalog18.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 18
        user_id = 8
        parameters = [datetime.now() - timedelta(days=9) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Для тех кому данное направление будет интересно , очень крутая книга """]
        insert_sale(apps, parameters)
        catalog_id = 18
        user_id = 9
        parameters = [datetime.now() - timedelta(days=8) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 4, """На фото казалась больше, но качество бумаги и обложки ,выше всяких похвал !!!"""]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [7, get_category(apps, "Бизнес-литература"), get_author(apps, "Шестакова Евгения Сергеевна"), "Говори красиво и уверенно. Постановка голоса и речи", """Что такое наш голос? Это прежде всего инструмент. Музыкальный, тонко устроенный, сложный, неповторимый. Можно быть серой мышкой с тихим, завышенным, неярким и плоским голосом, а можно играть первую скрипку в оркестре – каждый выбирает для себя.
Задача этой книги – повышение КПД каждого человека через развитие голоса. Это инструмент успешности – мощный и уникальный. Книга поможет вам понять себя, свои желания, свой голос, настроить его и полюбить. Мы поэтапно, глава за главой, урок за уроком научим обращаться с этим волшебным инструментом и использовать его богатые возможности на все 100 или даже 200%.
Книга построена по принципу тренинга, где в каждом блоке раскрывается новая тема. Между блоками есть связки, домашние задания и вопросы для самоконтроля. Вы сможете самостоятельно продиагностировать свой голос, а также ответить на вопрос, который интересует, пожалуй, большинство людей: а какой же у меня голос?
С помощью необычных, интересных заданий и листов контроля вы сможете исправить многие недостатки, присутствующие в вашей речи, и закрепить полученный результат. Надеемся, что благодаря такому подходу вы сможете изменить свой голос, усовершенствовать его и победить страх перед аудиторией.""", 401, 10, "шт.", "images/catalog19.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 19
        user_id = 10
        parameters = [datetime.now() - timedelta(days=8) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Хорошо написана книга.Дыхательная зарядка для диафрагмы ,упражнения для мышц голосового аппарата и его строение .Зарядка для связок и многое другое в этой книге.Спасибо вам Евгения за такую книгу.."""]
        insert_sale(apps, parameters)
        catalog_id = 19
        user_id = 11
        parameters = [datetime.now() - timedelta(days=7) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Очень полезная книжка, для тех кто хочет выступать со сцены."""]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [7, get_category(apps, "Бизнес-литература"), get_author(apps, "Рызов Игорь Романович"), "Кремлевская школа переговоров", """«Кремлевская школа переговоров», зародившаяся в 20-е годы минувшего века, стала одной из самых жестких переговорных школ в истории. Ее принципами руководствовались советские дипломаты, которым приходилось налаживать международные отношения СССР в условиях тотальной неприязни и недоверия. Зачастую они прибегали к самым агрессивным переговорным тактикам. Освоить все постулаты «Кремлевской школы» вам поможет эта книга.
С ней вы научитесь: 
• Выходить победителем из любых переговоров.
• Контролировать свои эмоции.
• Превращать борьбу в сотрудничество.
• Манипулировать своим оппонентом.
• Вести переговоры в разных странах, не допуская фатальных ошибок.""", 303, 10, "шт.", "images/catalog20.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 20
        user_id = 12
        parameters = [datetime.now() - timedelta(days=6) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Много полезной информации не только для продавцов, но и для жизни. Много примеров. """]
        insert_sale(apps, parameters)
        catalog_id = 20
        user_id = 13
        parameters = [datetime.now() - timedelta(days=5) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Очень по делу, интересно без воды."""]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [7, get_category(apps, "Научная литература"), get_author(apps, "Перельман Яков Исидорович"), "Занимательная физика", """Физика — это не обязательно формулы, задачи и учебники. По крайней мере, когда о ней рассказывает Яков Перельман. С помощью увлекательных опытов он объясняет, как устроен наш мир с точки зрения науки.
"Занимательная физика" — это лучшая отечественная книга о физике для всей семьи. С помощью увлекательных опытов и интересных историй Яков Перельман рассказывает о том, как устроен наш мир с точки зрения науки. А многие описанные здесь опыты вы сможете провести дома.
Как работает двигатель? Почему мы видим и слышим мир вокруг нас? Что будет, если в автомобиль на полном ходу прилетит арбуз? Что такое инерция?
Книга содержит около сотни иллюстраций и подойдет для чтения как взрослым, так и детям.""", 393, 10, "шт.", "images/catalog21.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 21
        user_id = 14
        parameters = [datetime.now() - timedelta(days=3) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Отличная книга!"""]
        insert_sale(apps, parameters)
        catalog_id = 21
        user_id = 15
        parameters = [datetime.now() - timedelta(days=2) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Очень занимательная книга!"""]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [8, get_category(apps, "Научная литература"), get_author(apps, "Антонин Марк Аврелий"), "Наедине с собой", """"Наедине с собой. Размышления" — сборник афористических мыслей Марка Аврелия, написанный им на греческом языке (койне) в 70-е годы II века во время войны на дунайской границе. Он пользовался несомненным успехом в позднеантичное время,  а в XVI веке  возродился в европейских философских кругах.
Эти личные записи отражают упорное стремление императора не только руководствоваться в своем мироощущении учением стоиков, но и развивать его дальше, назвав ведущим началом в человеке не душу, но разум, который нужно привести в согласие с природой целого, достигнув таким образом бесстрастия. """, 225, 10, "шт.", "images/catalog22.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 22
        user_id = 16
        parameters = [datetime.now() - timedelta(days=30) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Очень понравилось, всем советую. За свои деньги качество бумаги соответствует """]
        insert_sale(apps, parameters)
        catalog_id = 22
        user_id = 17
        parameters = [datetime.now() - timedelta(days=29) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Симпатичное небольшое издание, хорошее качество за свою цену. """]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [8, get_category(apps, "Научная литература"), get_author(apps, "Ницше Фридрих Вильгельм"), "Так говорил Заратустра", """Один из самых популярных и значимых трудов Фридриха Ницше о сверхчеловеке, Боге, религии и честному пути к себе. 
Будучи непонятым современниками в XIX веке, сегодня Ницше является одним из главных авторитетов в мире философии, его трактаты входят в обязательную программу всех ведущих вузов мира, им зачитывается весь научный мир и любой человек, пытающийся постичь истинный смысл жизни. 
ТЭГИ. Фридрих Ницше/ По ту сторону добра и зла/ Антихрист/ Так говорил Заратустра/ Генеалогия морали/ Воля к власти/ Карл Юнг/ Зигмунд Фрейд/ Уильям Шекспир/ Иоганн Гете/ Аристотель/ Философия/ Концепция сверхчеловека/ немецкий философ/ Заратуштра/ перспективизм/ экзистенциализм/ постмодернизм/ постструктурализм/ философский роман/ антитеизм/ воля к власти""", 226, 10, "шт.", "images/catalog23.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 23
        user_id = 18
        parameters = [datetime.now() - timedelta(days=27) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Подача материала и манера письма:Очень увлекательная
Сюжет:Захватывающий
Внешнее оформление:Красивое"""]
        insert_sale(apps, parameters)
        catalog_id = 23
        user_id = 19
        parameters = [datetime.now() - timedelta(days=26) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Отличная удобная лёгкая книга минусов не заметил, самая приятная которую я держал в руках"""]
        insert_sale(apps, parameters)
        #parameters = [datetime.now() - timedelta(days=25) + timedelta(minutes=random.randint(1, 240)), catalog_id, user_id, "Вопрос?", "Ответ"]		
        #insert_question(apps, parameters) 

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [8, get_category(apps, "Научная литература"), get_author(apps, "Элиаде Мирча"), "История веры и религиозных идей: от каменного века до элевсинских мистерий.", """Данный труд является классическим образцом исследования в области истории религии. Религиозные идеи представлены здесь не только в хронологическом порядке, но и объединены единым пониманием многообразия религиозной жизни всех культур и континентов. Элиаде виртуозно владеет методами сравнительной антропологии и демонстрирует общие тенденции в развитии религиозных идей. "Для историка религий знаменательно всякое проявление священного: каждый ритуал, каждый миф, каждое верование и каждый образ божества отражают опыт священного и потому несут в себе понятия бытия, смысла, истины".
Книга охватывает период от магических миров каменного века до религий древних цивилизаций и религии библейского откровения: "На самых архаических уровнях культуры жить, как подобает человеку, - само по себе есть религиозное действо, потому что принятие пищи, половые отношения и труд имеют сакраментальную ценность.""", 776, 10, "шт.", "images/catalog24.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 24
        user_id = 20
        parameters = [datetime.now() - timedelta(days=24) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """каменный век и элевсинские мистерии ребят. всем читать и наслаждаться """]
        insert_sale(apps, parameters)
        catalog_id = 24
        user_id = 21
        parameters = [datetime.now() - timedelta(days=23) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 4, """Качество бумаги:Нормальное
Внешнее оформление:Обычное
Подача материала и манера письма:Очень увлекательная"""]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [9, get_category(apps, "Научная литература"), get_author(apps, "Сурдин Владимир Георгиевич"), "Астрономия планетных систем", """Книга посвящена основам той части астрономии, которая связана с изучением объектов Солнечной системы — планет, их спутников, астероидов и комет, — а также с поиском и изучением экзопланет. В ней описаны основные астрономические приборы, системы координат и счёта времени на Земле и на других планетах. Рассказано о движении планет и традициях наименования небесных объектов.
Книга содержит новейшие данные, полученные с помощью наземной и космической аппаратуры, и будет полезна школьникам старших классов, студентам и всем, кто интересуется астрономией.""", 1089, 10, "шт.", "images/catalog25.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 25
        user_id = 22
        parameters = [datetime.now() - timedelta(days=21) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Владимир Георгиевич великолепен. Книга в отличном состоянии (и ждёт возможности подписать её у автора)"""]
        insert_sale(apps, parameters)
        catalog_id = 25
        user_id = 3
        parameters = [datetime.now() - timedelta(days=20) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Интересно, познавательно, просто Космос!!!!!"""]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [9, get_category(apps, "Детская литература"), get_author(apps, "Жвалевский Андрей Валентинович, Пастернак Евгения Борисовна"), "Время всегда хорошее. повесть.", """Что будет, если девчонка из 2018 года вдруг окажется в 1980 году? А мальчик из 1980 года перенесется на ее место? Где лучше? И что такое "лучше"? Где интереснее играть: на компьютере или во дворе? Что важнее: свобода и раскованность в чате или умение разговаривать, глядя в глаза друг другу? И самое главное - правда ли, что "время тогда было другое"? А может быть, время всегда хорошее и, вообще, всё зависит только от тебя.""", 333, 10, "шт.", "images/catalog26.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 26
        user_id = 4
        parameters = [datetime.now() - timedelta(days=18) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 4, """Читала будучи взрослой первые издания, купила подростку, как отметил, что хоть и обновили издание, но все равно чувствуется несовременность в подачи настоящего. """]
        insert_sale(apps, parameters)
        catalog_id = 26
        user_id = 5
        parameters = [datetime.now() - timedelta(days=17) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Дочери очень понравилась. Переплет мягкий, легко было следить сколько прочитано страниц."""]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [9, get_category(apps, "Детская литература"), get_author(apps, "Булычев Кир"), "Сто лет тому вперед", """"Сто лет тому вперед" — жемчужина детской фантастики, история, любимая уже несколькими поколениями читателей. Головокружительные приключения Коли и Алисы не оставят равнодушными и современных школьников! 
Любопытный сверх меры шестиклассник Коля нашел у соседа машину времени и случайно оказался в 2082 году. Там он познакомился с исследовательницей инопланетной фауны Алисой Селезневой и случайно перехватил у космических пиратов прибор для чтения мыслей — миелофон. 
Спасаясь, Коля сбежал обратно в Москву, в 1976 год. Теперь бандиты-инопланетяне преследуют мальчика, а Алиса отправляется в прошлое искать Колю и важное научное устройство… 
Читайте о невероятных приключениях Коли из прошлого и Алисы из будущего в повести "Сто лет тому вперед". Эта и другие книги нашей "Советской серии" Издательства Clever станут идеальным пополнением библиотеки каждого дома, где растет юный читатель.""", 304, 10, "шт.", "images/catalog27.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 27
        user_id = 6
        parameters = [datetime.now() - timedelta(days=15) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Книгу увидел в книжном магазине. Прочитал аннотацию, заинтреговал сюжет. Решил заказать. Может подойти для прочтения и взрослым и детям. Для тех кто любит фантазировать и любопытный ко всему новому. Книга в твёрдом переплёте, есть черно белые картинки, шрифт читаемый, газетного качества страницы. Рекомендую для прочтения. """]
        insert_sale(apps, parameters)
        catalog_id = 27
        user_id = 7
        parameters = [datetime.now() - timedelta(days=14) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Ооооочень хорошая книжка... После просмотра фильма Гостья из будущего, поняла, что нужно прочесть. Не оторваться от чтения."""]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [10, get_category(apps, "Детская литература"), get_author(apps, "Гайдар Аркадий Петрович"), "Тимур и его команда.", """Повесть «Тимур и его команда» была написана в 1940 году и сразу же стала любимой книгой миллионов юных читателей, а тимуровское движение – бескорыстно помогать тем, кто нуждается, – буквально захватило всю страну. Тайно совершая свои добрые дела, тимуровцы оставляли на воротах дома знак такого покровительства — пятиконечную звезду, олицетворявшую беззаветную любовь к Родине и готовность её защищать. Книга Гайдара пронизана верой в светлое будущее, может, поэтому герои его живут и сегодня. Все произведения в серии «Чтение — лучшее учение» публикуются в полном объеме без сокращений и адаптации.
Красочные приключения с иллюстрациями для малышей помогут ребенку лучше представить сюжеты историй и приключений героев, развить фантазию и воображение. Совместное чтение и обсуждение сюжетов и приключений героев книги поможет мальчикам и девочкам пополнить словарный запас и развить речь, а красивые картинки увлекут внимание ребенка.""", 176, 10, "шт.", "images/catalog28.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 28
        user_id = 1
        parameters = [datetime.now() - timedelta(days=12) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Замечательная книга. """]
        insert_sale(apps, parameters)
        catalog_id = 28
        user_id = 2
        parameters = [datetime.now() - timedelta(days=11) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Книга в хорошем качестве, рекомендую продавца"""]
        insert_sale(apps, parameters)
        #parameters = [datetime.now() - timedelta(days=10) + timedelta(minutes=random.randint(1, 240)), catalog_id, user_id, "Вопрос?", "Ответ"]		
        #insert_question(apps, parameters) 

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [10, get_category(apps, "Детская литература"), get_author(apps, "Твен Марк"), "Приключения Тома Сойера", """Том Сойер – озорной и непоседливый мальчишка, его хлебом не корми, дай только совершить какую-нибудь шалость. Даже наказание Том умело превращает в развлечение. Его неугомонный характер постоянно втягивает мальчишку в разные приключения, порой очень опасные. Тому предстоит проявить всё свою смелость и сделать сложный выбор: спасти от виселицы невинного человека и опасаться мести настоящего убийцы, или промолчать, испытывать муки совести, но не бояться за свою жизнь.""", 268, 10, "шт.", "images/catalog29.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 29
        user_id = 3
        parameters = [datetime.now() - timedelta(days=9) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Отличная книга, хорошо читается. Есть иллюстрации. Качественная и приятная обложка. """]
        insert_sale(apps, parameters)
        catalog_id = 29
        user_id = 4
        parameters = [datetime.now() - timedelta(days=8) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 4, """Книга с красочными иллюстрациями, плотной бумагой и чётким шрифтом. Товар доставлен быстро и в указанный срок. Спасибо."""]
        insert_sale(apps, parameters)

        # Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        parameters = [10, get_category(apps, "Детская литература"), get_author(apps, "Губарев Виталий"), "Королевство кривых зеркал", """Добрая, умная и необычайно увлекательная сказочная повесть Виталия Губарева «Королевство кривых зеркал» – одна из самых любимых детских книг в нашей стране, давно ставшая классикой. В ней пятиклассница Оля волшебным образом попадает в зазеркалье, где всё наоборот. Чтобы вернуться домой, ей придется пройти множество испытаний. И это не просто испытания – это проверка на характер и умение дружить. Прочитав эту книгу, каждый поймет: чтобы узнать, кто ты есть на самом деле, стоит посмотреть на себя со стороны.""", 316, 10, "шт.", "images/catalog30.jpg"]
        insert_catalog(apps, parameters)  
        # Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        catalog_id = 30
        user_id = 5
        parameters = [datetime.now() - timedelta(days=6) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Шикарная книжка, гибкая обложка. Сын в восторге , главы отзеркалены спасибо за такую фишку! И картинки все супер . Рекомендую """]
        insert_sale(apps, parameters)
        catalog_id = 30
        user_id = 6
        parameters = [datetime.now() - timedelta(days=5) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Хорошая добрая книжка"""]
        insert_sale(apps, parameters)

        ## Каталог        parameters - товар, (накладная, категория, название, описание, цена, количество, фото)
        #parameters = [11, get_category(apps, "Категория"), "Название", """Описание""", 1200, 10, "шт.", "images/catalog28.jpg"]
        #insert_catalog(apps, parameters)  
        ## Добавить продажу товар и отзывы parameters_sale (дата, catalog.id, catalog.price, количество, пользователь, адрес оценка, отзыв)
        #catalog_id = 28
        #user_id = 1
        #parameters = [datetime.now() - timedelta(days=12) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Отзыв."""]
        #insert_sale(apps, parameters)
        #catalog_id = 28
        #user_id = 2
        #parameters = [datetime.now() - timedelta(days=11) + timedelta(minutes=random.randint(1, 240)), catalog_id, dict_catalog_price.get(catalog_id), 1, user_id, get_adres(TRUE), 5, """Отзыв."""]
        #insert_sale(apps, parameters)
        #parameters = [datetime.now() - timedelta(days=10) + timedelta(minutes=random.randint(1, 240)), catalog_id, user_id, "Вопрос?", "Ответ"]		
        #insert_question(apps, parameters) 

        print("Созданы Каталог товаров + продажа + отзывы + вопросы и ответы")
        
        # Новости
        parameters = [datetime.now() - timedelta(days=15) + timedelta(minutes=random.randint(1, 240)), "В Казани открылся Всероссийский библиотечный конгресс", """В Казани открылся Всероссийский библиотечный конгресс: Ежегодная XXVIII конференция Российской библиотечной ассоциации. Здесь собрались более 1500 участников не только со всех регионов РФ, но и из 12 стран мира.
Международный статус форум обрел впервые и неслучайно. Главная тема конгресса - "Библиотека в многополярном мире". В Казань, которая сейчас носит титул библиотечной столицы России, прибыли гости из Индии, Китая, Кубы, Сербии, Азербайджана, Армении, Беларуси, Казахстана, Киргизии, Таджикистана и Узбекистана.""", "images/news1.jpg" ]
        insert_news(apps, parameters)

        parameters = [datetime.now() - timedelta(days=14) + timedelta(minutes=random.randint(1, 240)), "Объявлен шорт-лист иностранной номинации премии \"Ясная Поляна\"", """На церемонии, прошедшей 21 мая в Овальном зале Библиотеки иностранной литературы, жюри премии "Ясная Поляна" огласило список произведений, вошедших в шорт-лист. Об этом сообщает портал ГодЛитературы.РФ.
Из 27 книг, вошедших в лонг-лист премии, были выбраны следующие:
Клаудиа Пиньейро. Элена знает. - М.: Дом историй, 2023
Чухе Ким. Звери малой земли. - М.: Inspiria, 2024
Штефани фор Шульте. Мальчик с черным петухом. - Казахстан: Фолиант, 2024
Даниэль Шпек. Улица Яффо. - М.: Фантом Пресс, 2022
Хуан Габриэль Васкес. Тайная история Костагуаны. - М.: Лайвбук, 2023
Ма Боюн. Зоопарк на краю света. - М.: Лайвбук, 2023
Ольга Токарчук. Книги Якова. - М.: Эксмо, 2023
Абрахам Вергезе. Завет воды. - М.: Фантом Пресс, 2024
Мохамед Мбугар Сарр. В тайниках памяти. - М.: Синдбад, 2023
Мишель Уэльбек. Уничтожить. - М.: Corpus, 2023""", "images/news2.jpg" ]
        insert_news(apps, parameters)

        parameters = [datetime.now() - timedelta(days=13) + timedelta(minutes=random.randint(1, 240)), "В Иркутске впервые прошел новый книжный фестиваль \"КнигаМай\"", """Новый книжный фестиваль "КнигаМай" прошел в Иркутске в выходные. Он проводился в рамках проекта "Читающая Россия", созданного по инициативе Министерства цифрового развития, связи и массовых коммуникаций РФ.
На площадке "КнигаМая" собрались представители более 70 издательств со всей России и известные авторы: Василий Авченко, Миясат Муслимова, Анастасия Астафьева, Ислам Ханипаев и другие. Творческие встречи с писателями и поэтами, мастер-классы, викторины, презентации одновременно в режиме нон-стоп шли на четырех площадках.
- Наш книжный фестиваль "КнигаМарт", который мы проводим уже шесть лет, - отметила директор "Молчановки" Лариса Сулейманова. - Единственное, чего не хватало, - большой книжной ярмарки под открытым небом. И вот наша мечта воплотилась. Возможно, наш фестиваль для кого-то станет началом знакомства с новой хорошей литературой. Здесь каждый найдет что почитать.""", "images/news3.jpg" ]
        insert_news(apps, parameters)

        parameters = [datetime.now() - timedelta(days=12) + timedelta(minutes=random.randint(1, 240)), "В Казани библиотекари из 12 стран обсуждают роль книги в мире", """Всероссийский библиотечный конгресс проходит в Казани. Впервые форум обрел международный статус и собрал 1500 участников со всей России и гостей из 12 стран.
Главная тема встречи "Библиотека в многополярном мире". В Казань прибыли делегаты из Индии, Китая, Кубы, Сербии, Азербайджана, Армении, Беларуси, Казахстана, Киргизии, Таджикистана и Узбекистана. Президент Российской библиотечной ассоциации Михаил Афанасьев подчеркнул, что конгресс является вершиной деятельности библиотекарей. "Это то место, где мы проверяем себя и убеждаемся в том, что мы единое сообщество в независимости от того, где работаем - в сельском филиале, национальной, школьной, тюремной или военной библиотеке".""", "images/news4.jpg" ]
        insert_news(apps, parameters)

        parameters = [datetime.now() - timedelta(days=11) + timedelta(minutes=random.randint(1, 240)), "В Калининграде представили новый трехтомник Канта", """Под знаком 300-летия со дня рождения великого философа Иммануила Канта в самом западном регионе страны представили уникальный трехтомник. В новое издание Канта на русском вошли не только популярные работы мыслителя, но и новые переводы его текстов с немецкого или латыни. Пробный тираж отправят в научные библиотеки России.
Над изданием трудились калининградские и московские ученые. Каждый том снабдили обстоятельными предисловиями и комментариями ведущих российских специалистов по Канту Алексея Круглова, Алексея Жаворонкова, Андрея Судакова, Вадима Чалого, а также представителей молодого поколения кантоведов.
"Эти тексты позволяют проследить эволюцию кантовских концепций антропологии и философии религии, прояснить исторический контекст его размышлений и некоторые сложные для понимания моменты в главных кантовских трудах", - рассказала научный директор Академии Кантианы БФУ имени И. Канта и ответственный редактор издания Нина Дмитриева.""", "images/news5.jpg" ]
        insert_news(apps, parameters)

        parameters = [datetime.now() - timedelta(days=10) + timedelta(minutes=random.randint(1, 240)), "Рукопись знаменитого романа пролежала в кубанской земле почти 60 лет", """История, приключившаяся в курортном кубанском городке Горячий Ключ, напоминает закрученный детектив. Она до сих пор окутана завесой тайны, разгадывать которую продолжают энтузиасты из Русского географического общества и поклонники творчества Даниила Андреева, сына писателя Леонида Андреева. А сотрудники исторического музея Горячего Ключа (он правопреемник первого музея Северного Кавказа, открытого 160 лет назад) гордятся обретением уникальной рукописи главного произведения Даниила Леонидовича - знаменитой мистической поэмы в прозе "Роза мира".
Даниил Андреев в годы Великой Отечественной войны служил в санитарной команде. В 1947 году его арестовали по "антисоветской" 58-й статье УК РСФСР и приговорили к 25 годам лагерей, но через десять лет освободили, а затем полностью реабилитировали.
"Роза мира" - это религиозно-философский трактат, в котором все религии рассматриваются как лепестки одной розы. Андреев начал писать роман в тюрьме (все написанное им ранее было уничтожено сразу после ареста. - Т.П.), а завершил его именно в Горячем Ключе, куда в 1958 году опального тогда литератора привезла жена, художница Алла Андреева. К этому времени оба вернулись из лагерей, где она провела девять лет. Там, в застенках, на клочках бумаги писатель создавал свою "Розу мира" и сумел передать жене черновик романа во время короткого свидания.""", "images/news6.jpg" ]
        insert_news(apps, parameters)

        parameters = [datetime.now() - timedelta(days=9) + timedelta(minutes=random.randint(1, 240)), "В Москве прошел вечер памяти к 100-летию со дня рождения Бориса Васильева", """В Москве в книжном клубе "Достоевский" прошел вечер к 100-летию со дня рождения писателя, драматурга и сценариста Бориса Васильева.
Вечер памяти был посвящен не только литературному наследию писателя, но и кинолентам по мотивам его произведений. Один из них - "А зори здесь тихие".
"Для работы над фильмом Борис Васильев и Станислав Ростоцкий пригласили бывших фронтовиков, работавших в кино. Это люди, которые видели настоящую войну, для которых это была их юность, святое и страшное время, когда они формировались и влюблялись, когда на их глазах умирали их товарищи, а они чудом выжили. Для них эта тема была святой, - рассказала актриса и первый заместитель председателя комитета Госдумы по культуре Елена Драпеко, которая снималась в этом фильме в роли рядовой Лизы Бричкиной. - Станислав Ростоцкий показывал нам хронику войны. Страшные кадры, которые ни в один фильм нельзя вставить. Он хотел, чтобы мы пропитались этим ощущением. То, что надо преодолеть".
Повесть Бориса Васильева "А зори здесь тихие" рассказывает о подвиге девушек-зенитчиц. Во время Великой Отечественной войны в противовоздушной обороне воевало больше всего девушек - около 177 тысяч. Они обороняли от вражеских налетов города, пути сообщения и другие важные объекты. Порой ценою собственной жизни.""", "images/news7.jpg" ]
        insert_news(apps, parameters)

        print("Созданы Новости")

    except Exception as error:
        print(error)



class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(new_data),
        migrations.RunSQL("""CREATE VIEW view_catalog AS
SELECT catalog.id, catalog.invoice_id, catalog.category_id, category.category_title AS category, catalog.author_id, author.author_name AS author, catalog.catalog_title, catalog.details, catalog.price, catalog.quantity, catalog.unit, (catalog.price*catalog.quantity) AS total, catalog.photo, 
(SELECT SUM(quantity) FROM sale WHERE sale.catalog_id = catalog.id) AS sale_quantity,
CASE 
WHEN (catalog.quantity - (SELECT SUM(quantity) FROM sale WHERE sale.catalog_id = catalog.id)) IS NULL 
THEN catalog.quantity 
ELSE (catalog.quantity - (SELECT SUM(quantity) FROM sale WHERE sale.catalog_id = catalog.id)) 
END
AS available,
(SELECT AVG(rating) FROM sale WHERE sale.catalog_id = catalog.id) AS avg_rating
FROM catalog LEFT JOIN category ON catalog.category_id = category.id
LEFT JOIN author ON catalog.author_id = author.id"""),
##        # SQLite
#        migrations.RunSQL("""CREATE VIEW view_sale AS
#SELECT sale.id, username, first_name, last_name, saleday, catalog_id, view_catalog.category, view_catalog.author, view_catalog.catalog_title, view_catalog.photo, sale.price, sale.quantity, sale.price*sale.quantity AS total, user_id, address, rating, sale.details,
#(SELECT strftime('%d.%m.%Y',deliveryday) || ' - ' || movement FROM delivery WHERE sale_id = sale.id AND deliveryday = (SELECT MAX(deliveryday) AS Expr1 FROM delivery AS S WHERE  (sale_id = sale.id) )) AS final
#FROM sale LEFT JOIN view_catalog ON sale.catalog_id = view_catalog.id
#LEFT JOIN auth_user ON sale.user_id = auth_user.id"""),
        # PostgreeSQL
        migrations.RunSQL("""CREATE VIEW view_sale AS
SELECT sale.id, username, first_name, last_name, saleday, catalog_id, view_catalog.category, view_catalog.author, view_catalog.catalog_title, view_catalog.photo, sale.price, sale.quantity, sale.price*sale.quantity AS total, user_id, address, rating, sale.details,
(SELECT to_char( deliveryday, 'DD.MM.YYYY') || ' - ' || movement FROM delivery WHERE sale_id = sale.id AND deliveryday = (SELECT MAX(deliveryday) AS Expr1 FROM delivery AS S WHERE  (sale_id = sale.id) )) AS final
FROM sale LEFT JOIN view_catalog ON sale.catalog_id = view_catalog.id
LEFT JOIN auth_user ON sale.user_id = auth_user.id"""),


    ]